version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
  pull-request-branch-name:
    separator: "-"
  groups:
    npm-dependencies:
      patterns:
      - "*"
  ignore:
  - update-types:
    - version-update:semver-major
  - dependency-name: "*"
